Repository Schmiddl99/experimenteverwaltung-i2, pull requests merged in 2021-01, with the labels that each got.

#62 Use Cases added in Ascii
  Dokumentationen/requirements/use-case_model.adoc
  Dokumentationen/requirements/use_case_01.inc.adoc
  Dokumentationen/requirements/use_case_02.inc.adoc
  Dokumentationen/requirements/use_case_03.inc.adoc
  Dokumentationen/requirements/use_case_04.inc.adoc
Labels: asciidoctor, documentation

#95 Projektplan + Iteration 2 Doku
  Dokumentationen/project_management/Rollenübersicht.adoc
  Dokumentationen/project_management/iteration_plan_02.adoc
  Dokumentationen/project_management/project_plan.adoc
Labels: documentation, project management

#85 updated Templates from the original Repo
  Dokumentationen/_includes/default-attributes.inc.adoc
  Dokumentationen/se1_belegabgabe_tI2.adoc
Labels: documentation

#66 Xx julius glossary updates
  Dokumentationen/requirements/Glossar.adoc
Labels: asciidoctor, documentation

#120 add test cases 8 - 10
  Dokumentationen/test/test_cases.adoc
Labels: documentation

#96 Add files via upload
  Dokumentationen/project_management/risk_list_neu.csv
Labels: documentation, project management

#117 TCs for the UCs about the Dozentenwoche have been created.
  Dokumentationen/test/test_cases.adoc
Labels: documentation

#140 90 tim iteration plan 3
  Dokumentationen/project_management/iteration_plan03.adoc
  Dokumentationen/project_management/iteration_plan_02.adoc
  Dokumentationen/requirements/vision.adoc
Labels: documentation, project management

#126 Überarbeitung der Iterationspläne
  Dokumentationen/project_management/iteration_plan03.adoc
  Dokumentationen/project_management/iteration_plan_02.adoc
Labels: documentation, project management

#137 Add files via upload
  Dokumentationen/project_management/Risk_List_25.01.2021.csv
Labels: documentation, project management

#163 Added TCs Templates for the SWR
  Dokumentationen/test/test_cases.adoc
Labels: documentation
